name: Deploy Status

on:
 pull_request_target:
   branches:
     - main
   types: [opened, labeled, synchronize]
 issues:
   types: [labeled, closed]

permissions:
 checks: read
 issues: read
 pull-requests: read
 statuses: write

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
         repository: 'simplybusiness/deploy-status-action'
         ref: 'v0.4.1'
     - uses: ruby/setup-ruby@v1
       with:
         bundler-cache: true # runs 'bundle install' and caches installed gems automatically                       
     - name: Deploy Status Action
       uses: simplybusiness/deploy-status-action@v0.4.1
       env:
         ISSUE_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
         AIRBRAKE_KEY: ${{secrets.GH_AIRBRAKE_KEY}}